### PR TITLE
Add new job posting for Semaphore Solutions

### PR DESCRIPTION
**Pull request by linleyf**
New PM job posting at https://jobs.lever.co/semaphoresolutions/2ef30c50-5ec1-48fd-9239-efbe821f390a

### CODE REVIEW

**Comment by jaddison** [comment]
Hi Linley,

We need to remove a couple of broken links:

- Sasquatch job link is dead
- Exapik appears to not exist anymore; their site is down, they don't appear to be active anymore either? A cursory google search doesn't show any results since mid last year for them...

**Comment by tristan-swu** [comment]
Hi @jaddison  - thanks for the comment - you're right. We recently updated master to remove those links.
@linleyf - if you want to merge master into this branch it should resolve these broken links for you. If you want a hand, please reach out! Cheers.

**Comment by forsilly** [comment]
Hi @jaddison  - thanks for the comment - you're right. We recently updated master to remove the broken links.
@linleyf - if you want to merge master into this branch it should resolve these broken links for you. If you want a hand, please reach out!

**Comment by forsilly** [comment]
Hi @jaddison  - thanks for the comment - you're right. We recently updated master to remove the broken links.
@linleyf - if you want to merge master into this branch it should resolve these broken links for you. If you want a hand, please reach out!

**Pull request merged**
