### PR TITLE
Added LlamaZOO Backend Dev, removed other broken links

### PR DESCRIPTION
**Pull request by victor-llz**

### CODE REVIEW

**Comment by victor-llz** [comment]
🤷 [---] Checking www.revela.io failed with error code 7

Any idea why the link checker fails for this site when running on the travis build server? The links exist and it passes when I run the link checker locally.

**Comment by maryam-dyspatch** [comment]
> 🤷 [---] Checking [www.revela.io](http://www.revela.io) failed with error code 7
> 
> Any idea why the link checker fails for this site when running on the travis build server? The links exist and it passes when I run the link checker locally.
> 
> EDIT: I guess kicking off the build again until it works is one option...

Hi Victor - that link times out for me when I check it manually and also appears to be doing so when run through the link checker. The error code represents the number of links that had errors, in this case there appear to be 7. See our doc [here](https://github.com/sendwithus/vic-startup-jobs/tree/master/link_checker#return-codes) for reference

**Comment by maryam-dyspatch** [comment]
> > 🤷 [---] Checking [www.revela.io](http://www.revela.io) failed with error code 7
> > Any idea why the link checker fails for this site when running on the travis build server? The links exist and it passes when I run the link checker locally.
> > EDIT: I guess kicking off the build again until it works is one option...
> 
> Hi Victor - that link times out for me when I check it manually and also appears to be doing so when run through the link checker. The error code represents the number of links that had errors, in this case there appear to be 7. See our doc [here](https://github.com/sendwithus/vic-startup-jobs/tree/master/link_checker#return-codes) for reference

Oh, weird I actually checked it again and it's working now which is why it's passing CI now as well. I wonder if that link in particular has some spurious availability?

**Comment by victor-llz** [comment]
Thanks Maryam! Yes, perhaps the link was not responding (or taking too long) for occasional requests... anyway, all is good. :)

**Comment by zevisert** [comment]
😅 Yep, that'd be us - we've been having some tough to trace down availability issues with our site the past few weeks. 

I wrote the link checker, and FWIW, the error code in the link checker's logs are references to cURL's return codes, https://curl.haxx.se/libcurl/c/libcurl-errors.html. In that case, `error code 7` that you saw refers to `CURLE_COULDNT_CONNECT`. 

The link checker itself has it's own return code, which is what's mentioned in the documentation link maryam shared. That's unclear for sure, and I've added some changes to the link checker docs in #220 along with some message classes for CURLcodes  7 and 28.

**Pull request merged**
