### PR TITLE
ci: use focal (Ubuntu 20.04)

### PR DESCRIPTION
**Pull request by zevisert**
The current builds are failing because HTTPS certificates are not up to date, eg lots of links look like this:

```log
$ link_checker/check.sh README.md
📊 Found 244 links in this document to test.
🔓 [---] watershed.co's SSL certificate seems invalid!
🔓 [---] boards.greenhouse.io's SSL certificate seems invalid!
🔓 [---] boards.greenhouse.io's SSL certificate seems invalid!
```

This is because the default build environment for travis is [Ubuntu 16.04](https://docs.travis-ci.com/user/reference/overview#linux). The 16.04 version number is actually a date, and Ubuntu Xenial was released in 2016! It's standard support window is now closed ([April 2021](https://wiki.ubuntu.com/Releases)).

Even though we update ca-certificates (the most common package that controls which root certificate authorities can be trusted), the version of ca-certificates for xenial hasn't been updated [since January](https://www.ubuntuupdates.org/package/core/xenial/main/security/ca-certificates)!

If we use Ubuntu 20.04 (the current long term support (LTS) release), then we should be good for another couple years.

### CODE REVIEW

**Comment by zevisert** [comment]
Ah bummer, still failed. I saw this locally with #267. I don't know what Audette is up to with their site, but I can't connect to it with curl.. I've tried UA spoofing, and even copying the request right from the browser as a curl command, but it still hangs every time..


This is the request copied straight from devtools, and while the page loads just fine in the browser, curl can't get a response at all.. Any ideas?

```shell
curl 'https://audette.io/' \
  -H 'authority: audette.io' \
  -H 'cache-control: max-age=0' \
  -H 'sec-ch-ua: "Microsoft Edge";v="95", "Chromium";v="95", ";Not A Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'dnt: 1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.44' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'sec-fetch-site: none' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-user: ?1' \
  -H 'sec-fetch-dest: document' \
  -H 'accept-language: en-GB,en;q=0.9,en-US;q=0.8' \
  -H 'if-none-match: "xEvuZw"' \
  --compressed
```

**Comment by zevisert** [comment]
Since this is probably going to hang out in a pending state until I can figure out how to get this site to respond, I sent an email to Audette, solely out of curiosity about what's going on here. We might end up hearing from @dmossie on this

**Comment by zevisert** [comment]
I've also tried `wget` and `node-fetch`, both are also unable to connect.. Though I did just notice that Audette.io is an ipv6 only website, and there's a [longstanding issue with WSL and IPV6 routing](https://github.com/microsoft/WSL/issues/4518) that I think is causing this for me locally, but that still doesn't explain why the same failure occurs on Travis

**Comment by demoore** [comment]
I'm getting something similar on Linux. What did work was curling https://**www.**audette.io. Can you update their link in this PR? I'm keen to get this out.

**Comment by zevisert** [comment]
Curious, yeah that'll work. I think this all comes down to the fact that without the `www.` the site is IPV6 only, and there's a couple upstream blockers for that still. I was finding some issues about it on Travis that also claimed there was no route for IPV6 addresses.

Curiously, `dig`ing for A vs AAAA records with and without the `www.` subdomain all come back with different records.

**Comment by zevisert** [comment]
That worked, just a normal missing posting now. Looks like one of the CrowdContent positions changed its URL while we were working on this. 

The `Editorial Content Manager` previously at https://www.crowdcontent.com/senior-project-manager/ now seems like it should be this https://www.crowdcontent.com/editorial-content-manager/ link. Want me to update that here too?

**Comment by demoore** [comment]
Yes please! Thanks for this @zevisert -- this should have been an easy fix. :sweat_smile:

**Comment by zevisert** [comment]
> this should have been an easy fix. 😅

Classic, will do!

**Comment by demoore** [comment]
Thanks again @zevisert!

**Comment by zevisert** [comment]
Ahaha right when we could have had the first successful job on main in months, one site has a temporary service disruption and and the job runs at the same time and reports as failed. Anticlimactic isn't it? Oh well, it still seems like some of the next ones should succeed! 😆

**Pull request merged**
