### PR TITLE
Migrate to github actions

### LINKED ISSUE #310: Travis build not running
I noticed the link_checker hasn't been running since Feb 2023. I wrote the bash-based link checker, so if there was something broken about it, feel free to let me know - although, I didn't set up the travis integration, I just wrote the code for the checker itself. I could also look into running with github actions instead of travis if that's more ideal?

Maybe related to #254 or #234.

### PR DESCRIPTION
**Pull request by zevisert**
Closes #310, removes Travis in favour of github actions instead

### CODE REVIEW

**Comment by zevisert** [comment]
Some admin on this repo might need to enable github actions to run here; for now you can see the run on our fork: https://github.com/revela-systems/vic-startup-jobs/actions/runs/8087421230/job/22099321365

**Comment by zevisert** [comment]
I could also wire up the results from the link checker as a comment on the PR instead of having to go into the build logs

**Comment by demoore** [comment]
@zevisert Could you? That would be _amazing_.

**Comment by zevisert** [comment]
Sure

**Comment by zevisert** [comment]
When I wrote the link checker a few years ago I alreaded added a `--markdown` flag for this exact reason haha

**Comment by zevisert** [comment]
Now just on you @demoore to enable github actions in this repo I think. I was testing in my fork, seems good to go: https://github.com/revela-systems/vic-startup-jobs/pull/2

**Comment by demoore** [comment]
Thank you @zevisert ! Merging in now.

**Pull request merged**
