### PR TITLE
Updated jobs for Tutela

### PR DESCRIPTION
**Pull request by tutela**

### CODE REVIEW

**Comment by tutela** [comment]
Build failures were not my edits (other company's jobs).

*Might want to consider having this build run nightly or something to flag bad links out on an ongoing basis

**Comment by jaddison** [comment]
@tutela hey, thanks for submitting - and good suggestion. Maybe @bvanvugt can chime in on it/set it up. 

That said, we currently leave it up to everyone who's submitting new jobs to clean up broken links, even if they're for other companies - from the README:

>Running it before pushing up to Github allows you to remove broken job links from the list in addition to updating your own job postings.

Do you mind taking an extra minute to do so?

**Comment by tutela** [comment]
Semi-related, should we just focus on broken links?
or also suggest edits in terms of other potential issues?

**Comment by jaddison** [comment]
Thanks for the link edits, @tutela! If you have specific suggestions on how to improve things, please do suggest - but, as I see there's no issue tracker for this repo, I'm not sure on the best way to approach this. 🤔

**Comment by bvanvugt** [comment]
@tutela @jaddison I've enabled issues on this repo 👍

**Pull request merged**
